name: Snyk Security

on:
  push:
    branches: ["fix/security-Rajavel"]
  pull_request:
    branches: ["fix/security-Rajavel"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      # Checkout du code
      - uses: actions/checkout@v4

      # Setup du CLI Snyk
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Analyse SAST (Snyk Code) et génération du fichier SARIF
      - name: Snyk Code test
        run: snyk code test --sarif > snyk-code.sarif || true

      # Analyse Open Source (Snyk SCA) et monitoring
      - name: Snyk Open Source monitor
        run: snyk monitor --all-projects

      # Analyse Infrastructure as Code (si tu as des fichiers IaC)
      - name: Snyk IaC test
        run: snyk iac test --report || true

      # Upload des résultats SAST dans GitHub Code Scanning
      - name: Upload Snyk Code results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
