name: Détection de vulnérabilités Snyk

on: [push, pull_request]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Exécution du scan Snyk
        uses: snyk/actions/setup@v1
        with:
          token: ${{ secrets.SNYK_TOKEN }}
      
      - name: Lancer Snyk test
        run: snyk test --all-projects --severity-threshold=medium

      - name: Monitor Snyk
        run: snyk monitor --all-projects
