name: Snyk Scan

on:
  push:
    branches: ["main", "fix/**"]
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Snyk test
        uses: snyk/actions@master
        with:
          command: test --all-projects --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
