name: Détection de vulnérabilités Trivy

on: [push, pull_request]

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Exécution de Trivy
        uses: aquasecurity/trivy-action@v0.14.0
        with:
          scan-type: fs
          format: table
          exit-code: 1
          severity: MEDIUM,HIGH,CRITICAL
