name: Trivy Scan

on:
  push:
    branches: ["main", "fix/**"]
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@v0.35.0  # <-- derniÃ¨re version stable
        with:
          format: table
          severity: MEDIUM,HIGH,CRITICAL
          exit-code: 1
